repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: make-static
        name: Run make static
        entry: make static
        language: system
        pass_filenames: false
